### ISSUE TITLE
Help Needed : Linking Tenant to IDP

### ISSUE THREAD

**Issue by HanifAbRazak** [anarsultanov/keycloak-multi-tenancy#11]
Based on your readme file,

"To configure an IDP as tenant-specific, tenants' IDs should be added to the multi-tenancy.tenants configuration attribute of the IDP as a comma-separated list. This can be achieved using the standard [Keycloak REST API](https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#_identity_providers)."

I'm trying to figure out how to link tenant to IDP.

I successfully created 2 tenants by consuming {{keycloakUrl}}/auth/realms/{{realmName}}/tenants endpoint.

Then, I create new user, use the user email to for invitation for on of the client. From what I can see, the user will able to view the invitation when they login to Keycloak. Is there any way the user can view the invitation? like received an email?

I also created a Microsoftt IDP.

I'm strugling to to link created tenant to an IDP based on the description above. Can you please specify which endpoint from the Keycloak Rest API to use for this purpose and example of the payload?

**Comment by anarsultanov** [comment]
Hi @HanifAbRazak,

To link a created tenant to an Identity Provider (IDP), you should use the `PUT /admin/realms/{realm}/identity-provider/instances/{alias}` endpoint. Ensure that you include the full body obtained from a `GET` request to the same endpoint, and add the `multi-tenancy.tenants` configuration.

Here's an example:
```
PUT /admin/realms/{realm}/identity-provider/instances/{alias}

{
  "alias": "{alias}",
  "config": {
    "clientId": "{clientId}",
    "clientSecret": "{clientSecret}",
    "multi-tenancy.tenants": "tenant-1-id,tenant-2-id",
    // Other configuration properties...
  },
  // Other properties...
}
```

Hope this helps!

**Comment by anarsultanov** [comment]
Thank you for providing additional details, but it appears there might be a misunderstanding.
It's important to note that you cannot control which users can "use" the IdP, as any user linked to it is allowed to log in. What you can control is access to the specific tenant.

For example, if you have tenants named "99x" and "lol" with one user linked to each tenant through tenant membership, and you link the "99x" tenant to the "microsoft" IdP, both users can log in using the IdP if they exist in the IdP. However, only the user linked to the "99x" tenant will be able to proceed with authentication to the associated tenant, while the other user will encounter an error. 
To better understand this behavior, you can refer to the `IdentityProviderIntegrationTest`, which includes tests that illustrate these scenarios.

As for limiting IdP visibility in the UI based on tenant membership, if you're referring to the login page, this will not be possible since users are not yet logged in, and their tenant memberships are not known. However, you can consider using the `Login with SSO` authenticator instead of listing IdPs directly, as outlined in the [README](https://github.com/anarsultanov/keycloak-multi-tenancy#idp-and-sso-integration).
